/* Fuzzy inference system generated by qfiscgen.m for the qFIS engine*/
/* Generated : 31-Oct-2023 15:48:25 */
/* MATLAB Version: 9.11.0.1769968 (R2021b) */
/* Note: Based on the qFIS engine from https://github.com/kmilo17pet/qlibs */

#include <fuzzy_fis.h>
#include "qfis.h"

/* FIS Object */
static qFIS_t fuzzy;
/* I/O Fuzzy Objects */
static qFIS_Input_t fuzzy_inputs[ 2 ];
static qFIS_Output_t fuzzy_outputs[ 1 ];
/* I/O Membership Objects */
static qFIS_MF_t MFin[ 10 ], MFout[ 7 ];
/* I/O Names */
enum { e, edot };
enum { u };
/* I/O Membership functions tags */
enum { e_NB, e_NS, e_ZE, e_PS, e_PB, edot_NB, edot_NS, edot_ZE, edot_PS, edot_PB };
enum { u_NB, u_NM, u_NS, u_ZE, u_PS, u_PM, u_PB };
/* Rules of the inference system */
static const qFIS_Rules_t rules[] = { 
    QFIS_RULES_BEGIN
       IF e IS e_NB AND edot IS edot_NB THEN u IS u_NB END
       IF e IS e_NB AND edot IS edot_NS THEN u IS u_NB END
       IF e IS e_NB AND edot IS edot_ZE THEN u IS u_NM END
       IF e IS e_NB AND edot IS edot_PS THEN u IS u_NS END
       IF e IS e_NB AND edot IS edot_PB THEN u IS u_ZE END
       IF e IS e_NS AND edot IS edot_NB THEN u IS u_NB END
       IF e IS e_NS AND edot IS edot_NS THEN u IS u_NM END
       IF e IS e_NS AND edot IS edot_ZE THEN u IS u_NS END
       IF e IS e_NS AND edot IS edot_PS THEN u IS u_ZE END
       IF e IS e_NS AND edot IS edot_PB THEN u IS u_PS END
       IF e IS e_ZE AND edot IS edot_NB THEN u IS u_NM END
       IF e IS e_ZE AND edot IS edot_NS THEN u IS u_NS END
       IF e IS e_ZE AND edot IS edot_ZE THEN u IS u_ZE END
       IF e IS e_ZE AND edot IS edot_PS THEN u IS u_PS END
       IF e IS e_ZE AND edot IS edot_PB THEN u IS u_PM END
       IF e IS e_PS AND edot IS edot_NB THEN u IS u_NS END
       IF e IS e_PS AND edot IS edot_NS THEN u IS u_ZE END
       IF e IS e_PS AND edot IS edot_ZE THEN u IS u_PS END
       IF e IS e_PS AND edot IS edot_PS THEN u IS u_PM END
       IF e IS e_PS AND edot IS edot_PB THEN u IS u_PB END
       IF e IS e_PB AND edot IS edot_NB THEN u IS u_ZE END
       IF e IS e_PB AND edot IS edot_NS THEN u IS u_PS END
       IF e IS e_PB AND edot IS edot_ZE THEN u IS u_PM END
       IF e IS e_PB AND edot IS edot_PS THEN u IS u_PB END
       IF e IS e_PB AND edot IS edot_PB THEN u IS u_PB END
    QFIS_RULES_END
};
/* Rule strengths */
float rStrength[ 25 ] = { 0.0f };

/* Parameters of the membership functions */
static const float e_NB_p[] = { -2.0000f, -1.0000f, -0.5000f };
static const float e_NS_p[] = { -1.0000f, -0.5000f, 0.0000f };
static const float e_ZE_p[] = { -0.5000f, 0.0000f, 0.5000f };
static const float e_PS_p[] = { 0.0000f, 0.5000f, 1.0000f };
static const float e_PB_p[] = { 0.5000f, 1.0000f, 2.0000f };
static const float edot_NB_p[] = { -2.0000f, -1.0000f, -0.5000f };
static const float edot_NS_p[] = { -1.0000f, -0.5000f, 0.0000f };
static const float edot_ZE_p[] = { -0.5000f, 0.0000f, 0.5000f };
static const float edot_PS_p[] = { 0.0000f, 0.5000f, 1.0000f };
static const float edot_PB_p[] = { 0.5000f, 1.0000f, 2.0000f };
static const float u_NB_p[] = { -1.0000f };
static const float u_NM_p[] = { -0.6600f };
static const float u_NS_p[] = { -0.3300f };
static const float u_ZE_p[] = { 0.0000f };
static const float u_PS_p[] = { 0.3300f };
static const float u_PM_p[] = { 0.6600f };
static const float u_PB_p[] = { 1.0000f };

void fuzzy_init( void ){
    /* Set inputs */
    qFIS_InputSetup( fuzzy_inputs, e, -1.0000f, 1.0000f );
    qFIS_InputSetup( fuzzy_inputs, edot, -1.0000f, 1.0000f );
    /* Set outputs */
    qFIS_OutputSetup( fuzzy_outputs, u, 0.0000f, 1.0000f );
    /* Set membership functions for the inputs */
    qFIS_SetMF( MFin, e, e_NB, trimf, NULL, e_NB_p, 1.0f );
    qFIS_SetMF( MFin, e, e_NS, trimf, NULL, e_NS_p, 1.0f );
    qFIS_SetMF( MFin, e, e_ZE, trimf, NULL, e_ZE_p, 1.0f );
    qFIS_SetMF( MFin, e, e_PS, trimf, NULL, e_PS_p, 1.0f );
    qFIS_SetMF( MFin, e, e_PB, trimf, NULL, e_PB_p, 1.0f );
    qFIS_SetMF( MFin, edot, edot_NB, trimf, NULL, edot_NB_p, 1.0f );
    qFIS_SetMF( MFin, edot, edot_NS, trimf, NULL, edot_NS_p, 1.0f );
    qFIS_SetMF( MFin, edot, edot_ZE, trimf, NULL, edot_ZE_p, 1.0f );
    qFIS_SetMF( MFin, edot, edot_PS, trimf, NULL, edot_PS_p, 1.0f );
    qFIS_SetMF( MFin, edot, edot_PB, trimf, NULL, edot_PB_p, 1.0f );
    /* Set membership functions for the outputs */
    qFIS_SetMF( MFout, u, u_NB, constantmf, NULL, u_NB_p, 1.0f );
    qFIS_SetMF( MFout, u, u_NM, constantmf, NULL, u_NM_p, 1.0f );
    qFIS_SetMF( MFout, u, u_NS, constantmf, NULL, u_NS_p, 1.0f );
    qFIS_SetMF( MFout, u, u_ZE, constantmf, NULL, u_ZE_p, 1.0f );
    qFIS_SetMF( MFout, u, u_PS, constantmf, NULL, u_PS_p, 1.0f );
    qFIS_SetMF( MFout, u, u_PM, constantmf, NULL, u_PM_p, 1.0f );
    qFIS_SetMF( MFout, u, u_PB, constantmf, NULL, u_PB_p, 1.0f );

    /* Configure the Inference System */
    qFIS_Setup( &fuzzy, Sugeno,
    		fuzzy_inputs, sizeof(fuzzy_inputs),
			fuzzy_outputs, sizeof(fuzzy_outputs),
                MFin, sizeof(MFin), MFout, sizeof(MFout),
                rules, rStrength, 25u );
    qFIS_SetParameter( &fuzzy, qFIS_AND, qFIS_PROD );
    qFIS_SetParameter( &fuzzy, qFIS_Implication, qFIS_PROD );
    qFIS_SetParameter( &fuzzy, qFIS_Aggregation, qFIS_SUM );
}

void fuzzy_run( float *inputs, float *outputs ) {
    /* Set the crips inputs */
    qFIS_SetInput( fuzzy_inputs, e, inputs[ e ] );
    qFIS_SetInput( fuzzy_inputs, edot, inputs[ edot ] );

    qFIS_Fuzzify( &fuzzy );
    if ( qFIS_Inference( &fuzzy ) > 0 ) {
        qFIS_DeFuzzify( &fuzzy );
    }
    else {
        /* Error! */
    }

    /* Get the crips outputs */
    outputs[ u ] = qFIS_GetOutput( fuzzy_outputs, u );
}
