/* Fuzzy inference system generated by qfiscgen.m for the qFIS engine*/
/* Generated : 31-Oct-2023 15:48:25 */
/* MATLAB Version: 9.11.0.1769968 (R2021b) */
/* Note: Based on the qFIS engine from https://github.com/kmilo17pet/qlibs */

#ifndef FUZZY_FIS_H
#define FUZZY_FIS_H

#ifdef __cplusplus
    extern "C" {
#endif

    void fuzzy_init( void );
    void fuzzy_run( float *inputs, float *outputs );

#ifdef __cplusplus
    }
#endif

#endif /* FUZZY_FIS_H */
